const quotes = [
    '"Sometimes doing nothing makes way for everything." – Unknown',
    '"All of humanity’s problems stem from man’s inability to sit quietly in a room alone." – Blaise Pascal',
    '"Idleness is the beginning of all vices, but also the crown of all virtues." – Franz Kafka',
    '"Rest is not idleness, and to lie sometimes on the grass under trees on a summer’s day, listening to the murmur of water, or watching the clouds float across the sky, is by no means a waste of time." – John Lubbock',
    '"In the midst of movement and chaos, keep stillness inside of you." – Deepak Chopra',
    '"It is in moments of silence that we find ourselves." – Unknown',
    '"The monotony and solitude of a quiet life stimulates the creative mind." – Albert Einstein',
    '"The time you enjoy wasting is not wasted time." – Marthe Troly-Curtin',
    '"Rest and be thankful." – William Wordsworth',
    '"Sometimes the most productive thing you can do is relax." – Mark Black',
    '"The quieter you become, the more you can hear." – Ram Dass',
    '"To be idle is a short road to death and to be diligent is a way of life; foolish people are idle, wise people are diligent." – Buddha',
    '"Take rest; a field that has rested gives a bountiful crop." – Ovid',
    '"A little idleness is good for you; it gives you time to dream." – Unknown',
    '"Idleness is not doing nothing. Idleness is being free to do anything." – Floyd Dell',
    '"Sometimes, the most productive thing you can do is to rest." – Unknown',
    '"In rest, we find renewal." – Unknown',
    '"The greatest remedy for anger is delay." – Seneca',
    '"If you want to do something, you have to do nothing for a while." – Unknown',
    '"Idleness, like kisses, to be sweet must be stolen." – Jerome K. Jerome',
    '"A good rest is as good as a good deed." – John A. G. Mackay',
    '"Life is not a race. Take it slower. Hear the music before the song is over." – Unknown'
];